const AUTH_INVALID_CREDENTIALS = 'AUTH.INVALID_CREDENTIALS';

const EMAIL_INVALID = 'EMAIL.INVALID';

const FULL_NAME_INVALID = 'FULL_NAME.INVALID';
const FULL_NAME_IS_TOO_LONG = 'FULL_NAME.IS_TOO_LONG';

const PASSWORD_INVALID = 'PASSWORD.INVALID';

export {
  AUTH_INVALID_CREDENTIALS,
  EMAIL_INVALID,
  FULL_NAME_INVALID,
  FULL_NAME_IS_TOO_LONG,
  PASSWORD_INVALID,
};
