const ACCOUNT_NUMBER_INVALID = 'ACCOUNT_NUMBER.INVALID';
const AUTH_INVALID_CREDENTIALS = 'AUTH.INVALID_CREDENTIALS';

const CATEGORY_INVALID_NAME = 'CATEGORY.INVALID_NAME';

const EMAIL_INVALID = 'EMAIL.INVALID';

const FULL_NAME_INVALID = 'FULL_NAME.INVALID';
const FULL_NAME_IS_TOO_LONG = 'FULL_NAME.IS_TOO_LONG';
const FACTORY_UNEXPECTED_ERROR = 'FACTORY.UNEXPECTED_ERROR';

const MONEY_INVALID_AMOUNT = 'MONEY.INVALID_AMOUNT';
const MONEY_NEGATIVE_AMOUNT = 'MONEY.NEGATIVE_AMOUNT';
const MONEY_MUST_BE_INTEGER = 'MONEY.MUST_BE_INTEGER';
const MONEY_INSUFFICIENT_AMOUNT = 'MONEY.INSUFFICIENT_AMOUNT';

const PASSWORD_INVALID = 'PASSWORD.INVALID';

const TRANSACTION_TO_THE_SAME_ACCOUNT = 'TRANSACTION.TO_THE_SAME_ACCOUNT';
const TRANSACTION_WITH_INVALID_AMOUNT = 'TRANSACTION.INVALID_AMOUNT';

const USER_ID_INVALID = 'USER_ID.INVALID';

const POT_ID_INVALID = 'POT_ID_INVALID';

const BUDGET_ID_INVALID = 'BUDGET_ID_INVALID';

const ACCOUNT_INSUFFICIENT_FUNDS = 'ACCOUNT.INSUFFICIENT_FUNDS';

export {
  ACCOUNT_INSUFFICIENT_FUNDS,
  ACCOUNT_NUMBER_INVALID,
  AUTH_INVALID_CREDENTIALS,
  BUDGET_ID_INVALID,
  CATEGORY_INVALID_NAME,
  EMAIL_INVALID,
  FACTORY_UNEXPECTED_ERROR,
  FULL_NAME_INVALID,
  FULL_NAME_IS_TOO_LONG,
  MONEY_INSUFFICIENT_AMOUNT,
  MONEY_INVALID_AMOUNT,
  MONEY_MUST_BE_INTEGER,
  MONEY_NEGATIVE_AMOUNT,
  PASSWORD_INVALID,
  POT_ID_INVALID,
  TRANSACTION_TO_THE_SAME_ACCOUNT,
  TRANSACTION_WITH_INVALID_AMOUNT,
  USER_ID_INVALID,
};
