export type TransferErrorCode =
  (typeof TRANSFER_ERROR_CODES)[keyof typeof TRANSFER_ERROR_CODES];

export const TRANSFER_ERROR_CODES = {
  SOURCE_ACCOUNT_NOT_FOUND: 'TRANSFER.SOURCE_ACCOUNT.NOT_FOUND',
  DESTINATION_ACCOUNT_NOT_FOUND: 'TRANSFER.DESTINATION_ACCOUNT.NOT_FOUND',
} as const;
