export type FundsAllocationErrorCode =
  (typeof FUNDS_ALLOCATION_ERROR_CODES)[keyof typeof FUNDS_ALLOCATION_ERROR_CODES];

export const FUNDS_ALLOCATION_ERROR_CODES = {
  POT_ACCOUNT_MISMATCH: 'FUNDS_ALLOCATION.POT.ACCOUNT.MISMATCH',
  POT_NOT_FOUND: 'FUNDS_ALLOCATION.POT.NOT_FOUND',
  ACCOUNT_NOT_FOUND: 'FUNDS_ALLOCATION.ACCOUNT.NOT_FOUND',
} as const;
